#!/usr/bin/env bash

# load core modules
b.module.require 'task'


# define tasks
# <<TASK STUB>>

task="$1"
shift

# define depend list here
# <<DEPENDENCY STUB>>
# dependency list. if these tools aren't installed grove will exit
# b.depends_on "sed grep gawk awk"

[ -n "$task" ] && b.task.run "${task}" "$@"
